{{- if and (.Values.thanos.enabled) (.Values.thanos.query.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: thanos-store-gateway
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: grpc
      port: 10901
      targetPort: grpc
  selector:
    thanos-store-api: "true" # Allows us to do local DNS SRV lookup: thanos-store-api.<namespace>.svc
{{- end }}
