{{- if .Values.tls.enabled }}
apiVersion: v1
data:
  {{ .Values.tls.keyFile }}: "{{ .Values.tls.keyValue }}"
  {{ .Values.tls.certFile }}: "{{ .Values.tls.certValue }}"
kind: Secret
metadata:
  name: {{ template "grafana.fullname" . }}-tls
  namespace: {{ .Release.Namespace }}
{{- end }}